name: Build LaTeX document

on: ['push', 'release']

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Set up Git repository
        uses: actions/checkout@v2
      - 
        name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: src
          root_file: index.tex
          args: -pdf -bibtex --shell-escape -file-line-error -halt-on-error -interaction=nonstopmode
      - 
        name: Generate Filename
        run: |
          reponame=$(echo "${{ github.repository }}" | sed -r 's/\//-/g')
          sha=$(printf "%.7s" "${{ github.sha }}" )
          echo "filename=${reponame}_${sha}.pdf" >> $GITHUB_ENV
      - 
        name: Rename Output File
        run: mv src/index.pdf "src/${{ env.filename }}"
      - 
        uses: actions/upload-artifact@v2
        with:
          name: LaTeX to PDF
          path: "src/${{ env.filename }}"

  upload_to_release:
    runs-on: ubuntu-latest
    needs: [build_latex]
    if: ${{ github.ref_type == 'tag' }}
    steps:
      - 
        name: Set up Git repository
        uses: actions/checkout@v2
      -
        name: Download build
        uses: actions/download-artifact@v3
        with:
          name: LaTeX to PDF
      - 
        name: Generate Filename
        run: |
          reponame=$(echo "${{ github.repository }}" | sed -r 's/\//-/g')
          tag=$(echo "${{ github.ref }}" | sed -r 's/refs\/tags\///g')
          echo "filename=${reponame}_${tag}.pdf" >> $GITHUB_ENV
      - 
        name: Rename File
        run: mv ${{ jobs.build_latex.env.filename }} ${{ env.filename }}
      -
        name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: ${{ env.filename }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        

