name: Build LaTeX document

on:
  push:
    branches:
      - "feat-github-action"

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: src
          root_file: index.tex
          args: -pdf -bibtex --shell-escape -file-line-error -halt-on-error -interaction=nonstopmode
      - run: echo
      - name: Rename Generated File
        run: |
          echo "${{ github.repository }}" | sed -r 's/\//-/g'
          mv src/index.pdf src/index2.pdf
      - uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: src/index2.pdf